// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-import-from-notebooklm'
  | 'menuitem-n2z-settings'
  | 'menuitem-sync-to-notebooklm'
  | 'pref-default-tags'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-max-file-size'
  | 'pref-note-format'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
